/**
 * This class is generated by jOOQ
 */
package test.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public class TestTable12Record extends org.jooq.impl.UpdatableRecordImpl<test.schema.tables.records.TestTable12Record> {

	private static final long serialVersionUID = 589241816;

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setTestTableId(java.lang.Long value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_ID, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Long getTestTableId() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_ID);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD100</code>
	 */
	public void setTestTableField100(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD100, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD100</code>
	 */
	public java.lang.String getTestTableField100() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD100);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD110</code>
	 */
	public void setTestTableField110(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD110, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD110</code>
	 */
	public java.lang.String getTestTableField110() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD110);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD120</code>
	 */
	public void setTestTableField120(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD120, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD120</code>
	 */
	public java.lang.String getTestTableField120() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD120);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD130</code>
	 */
	public void setTestTableField130(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD130, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD130</code>
	 */
	public java.lang.String getTestTableField130() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD130);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD140</code>
	 */
	public void setTestTableField140(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD140, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD140</code>
	 */
	public java.lang.String getTestTableField140() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD140);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD150</code>
	 */
	public void setTestTableField150(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD150, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD150</code>
	 */
	public java.lang.String getTestTableField150() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD150);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD160</code>
	 */
	public void setTestTableField160(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD160, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD160</code>
	 */
	public java.lang.String getTestTableField160() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD160);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD170</code>
	 */
	public void setTestTableField170(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD170, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD170</code>
	 */
	public java.lang.String getTestTableField170() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD170);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD180</code>
	 */
	public void setTestTableField180(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD180, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD180</code>
	 */
	public java.lang.String getTestTableField180() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD180);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD190</code>
	 */
	public void setTestTableField190(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD190, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD190</code>
	 */
	public java.lang.String getTestTableField190() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD190);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD200</code>
	 */
	public void setTestTableField200(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD200, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD200</code>
	 */
	public java.lang.String getTestTableField200() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD200);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD210</code>
	 */
	public void setTestTableField210(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD210, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD210</code>
	 */
	public java.lang.String getTestTableField210() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD210);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD220</code>
	 */
	public void setTestTableField220(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD220, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD220</code>
	 */
	public java.lang.String getTestTableField220() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD220);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD230</code>
	 */
	public void setTestTableField230(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD230, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD230</code>
	 */
	public java.lang.String getTestTableField230() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD230);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD240</code>
	 */
	public void setTestTableField240(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD240, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD240</code>
	 */
	public java.lang.String getTestTableField240() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD240);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD250</code>
	 */
	public void setTestTableField250(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD250, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD250</code>
	 */
	public java.lang.String getTestTableField250() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD250);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD260</code>
	 */
	public void setTestTableField260(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD260, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD260</code>
	 */
	public java.lang.String getTestTableField260() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD260);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD270</code>
	 */
	public void setTestTableField270(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD270, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD270</code>
	 */
	public java.lang.String getTestTableField270() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD270);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD280</code>
	 */
	public void setTestTableField280(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD280, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD280</code>
	 */
	public java.lang.String getTestTableField280() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD280);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD290</code>
	 */
	public void setTestTableField290(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD290, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD290</code>
	 */
	public java.lang.String getTestTableField290() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD290);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD300</code>
	 */
	public void setTestTableField300(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD300, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD300</code>
	 */
	public java.lang.String getTestTableField300() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD300);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD310</code>
	 */
	public void setTestTableField310(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD310, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD310</code>
	 */
	public java.lang.String getTestTableField310() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD310);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD320</code>
	 */
	public void setTestTableField320(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD320, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD320</code>
	 */
	public java.lang.String getTestTableField320() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD320);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD330</code>
	 */
	public void setTestTableField330(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD330, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD330</code>
	 */
	public java.lang.String getTestTableField330() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD330);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD340</code>
	 */
	public void setTestTableField340(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD340, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD340</code>
	 */
	public java.lang.String getTestTableField340() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD340);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD350</code>
	 */
	public void setTestTableField350(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD350, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD350</code>
	 */
	public java.lang.String getTestTableField350() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD350);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD360</code>
	 */
	public void setTestTableField360(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD360, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD360</code>
	 */
	public java.lang.String getTestTableField360() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD360);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD370</code>
	 */
	public void setTestTableField370(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD370, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD370</code>
	 */
	public java.lang.String getTestTableField370() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD370);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD380</code>
	 */
	public void setTestTableField380(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD380, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD380</code>
	 */
	public java.lang.String getTestTableField380() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD380);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD390</code>
	 */
	public void setTestTableField390(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD390, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD390</code>
	 */
	public java.lang.String getTestTableField390() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD390);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD400</code>
	 */
	public void setTestTableField400(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD400, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD400</code>
	 */
	public java.lang.String getTestTableField400() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD400);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD410</code>
	 */
	public void setTestTableField410(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD410, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD410</code>
	 */
	public java.lang.String getTestTableField410() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD410);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD420</code>
	 */
	public void setTestTableField420(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD420, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD420</code>
	 */
	public java.lang.String getTestTableField420() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD420);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD430</code>
	 */
	public void setTestTableField430(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD430, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD430</code>
	 */
	public java.lang.String getTestTableField430() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD430);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD440</code>
	 */
	public void setTestTableField440(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD440, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD440</code>
	 */
	public java.lang.String getTestTableField440() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD440);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD450</code>
	 */
	public void setTestTableField450(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD450, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD450</code>
	 */
	public java.lang.String getTestTableField450() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD450);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD460</code>
	 */
	public void setTestTableField460(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD460, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD460</code>
	 */
	public java.lang.String getTestTableField460() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD460);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD470</code>
	 */
	public void setTestTableField470(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD470, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD470</code>
	 */
	public java.lang.String getTestTableField470() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD470);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD480</code>
	 */
	public void setTestTableField480(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD480, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD480</code>
	 */
	public java.lang.String getTestTableField480() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD480);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD490</code>
	 */
	public void setTestTableField490(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD490, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD490</code>
	 */
	public java.lang.String getTestTableField490() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD490);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD500</code>
	 */
	public void setTestTableField500(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD500, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD500</code>
	 */
	public java.lang.String getTestTableField500() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD500);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD510</code>
	 */
	public void setTestTableField510(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD510, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD510</code>
	 */
	public java.lang.String getTestTableField510() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD510);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD520</code>
	 */
	public void setTestTableField520(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD520, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD520</code>
	 */
	public java.lang.String getTestTableField520() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD520);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD530</code>
	 */
	public void setTestTableField530(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD530, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD530</code>
	 */
	public java.lang.String getTestTableField530() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD530);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD540</code>
	 */
	public void setTestTableField540(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD540, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD540</code>
	 */
	public java.lang.String getTestTableField540() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD540);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD550</code>
	 */
	public void setTestTableField550(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD550, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD550</code>
	 */
	public java.lang.String getTestTableField550() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD550);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD560</code>
	 */
	public void setTestTableField560(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD560, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD560</code>
	 */
	public java.lang.String getTestTableField560() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD560);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD570</code>
	 */
	public void setTestTableField570(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD570, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD570</code>
	 */
	public java.lang.String getTestTableField570() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD570);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD580</code>
	 */
	public void setTestTableField580(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD580, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD580</code>
	 */
	public java.lang.String getTestTableField580() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD580);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD590</code>
	 */
	public void setTestTableField590(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD590, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD590</code>
	 */
	public java.lang.String getTestTableField590() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD590);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD600</code>
	 */
	public void setTestTableField600(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD600, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD600</code>
	 */
	public java.lang.String getTestTableField600() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD600);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD610</code>
	 */
	public void setTestTableField610(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD610, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD610</code>
	 */
	public java.lang.String getTestTableField610() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD610);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD620</code>
	 */
	public void setTestTableField620(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD620, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD620</code>
	 */
	public java.lang.String getTestTableField620() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD620);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD630</code>
	 */
	public void setTestTableField630(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD630, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD630</code>
	 */
	public java.lang.String getTestTableField630() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD630);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD640</code>
	 */
	public void setTestTableField640(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD640, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD640</code>
	 */
	public java.lang.String getTestTableField640() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD640);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD650</code>
	 */
	public void setTestTableField650(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD650, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD650</code>
	 */
	public java.lang.String getTestTableField650() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD650);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD660</code>
	 */
	public void setTestTableField660(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD660, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD660</code>
	 */
	public java.lang.String getTestTableField660() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD660);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD670</code>
	 */
	public void setTestTableField670(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD670, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD670</code>
	 */
	public java.lang.String getTestTableField670() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD670);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD680</code>
	 */
	public void setTestTableField680(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD680, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD680</code>
	 */
	public java.lang.String getTestTableField680() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD680);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD690</code>
	 */
	public void setTestTableField690(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD690, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD690</code>
	 */
	public java.lang.String getTestTableField690() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD690);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD700</code>
	 */
	public void setTestTableField700(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD700, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD700</code>
	 */
	public java.lang.String getTestTableField700() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD700);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD710</code>
	 */
	public void setTestTableField710(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD710, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD710</code>
	 */
	public java.lang.String getTestTableField710() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD710);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD720</code>
	 */
	public void setTestTableField720(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD720, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD720</code>
	 */
	public java.lang.String getTestTableField720() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD720);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD730</code>
	 */
	public void setTestTableField730(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD730, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD730</code>
	 */
	public java.lang.String getTestTableField730() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD730);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD740</code>
	 */
	public void setTestTableField740(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD740, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD740</code>
	 */
	public java.lang.String getTestTableField740() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD740);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD750</code>
	 */
	public void setTestTableField750(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD750, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD750</code>
	 */
	public java.lang.String getTestTableField750() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD750);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD760</code>
	 */
	public void setTestTableField760(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD760, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD760</code>
	 */
	public java.lang.String getTestTableField760() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD760);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD770</code>
	 */
	public void setTestTableField770(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD770, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD770</code>
	 */
	public java.lang.String getTestTableField770() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD770);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD780</code>
	 */
	public void setTestTableField780(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD780, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD780</code>
	 */
	public java.lang.String getTestTableField780() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD780);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD790</code>
	 */
	public void setTestTableField790(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD790, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD790</code>
	 */
	public java.lang.String getTestTableField790() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD790);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD800</code>
	 */
	public void setTestTableField800(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD800, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD800</code>
	 */
	public java.lang.String getTestTableField800() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD800);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD810</code>
	 */
	public void setTestTableField810(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD810, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD810</code>
	 */
	public java.lang.String getTestTableField810() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD810);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD820</code>
	 */
	public void setTestTableField820(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD820, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD820</code>
	 */
	public java.lang.String getTestTableField820() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD820);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD830</code>
	 */
	public void setTestTableField830(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD830, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD830</code>
	 */
	public java.lang.String getTestTableField830() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD830);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD840</code>
	 */
	public void setTestTableField840(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD840, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD840</code>
	 */
	public java.lang.String getTestTableField840() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD840);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD850</code>
	 */
	public void setTestTableField850(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD850, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD850</code>
	 */
	public java.lang.String getTestTableField850() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD850);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD860</code>
	 */
	public void setTestTableField860(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD860, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD860</code>
	 */
	public java.lang.String getTestTableField860() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD860);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD870</code>
	 */
	public void setTestTableField870(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD870, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD870</code>
	 */
	public java.lang.String getTestTableField870() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD870);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD880</code>
	 */
	public void setTestTableField880(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD880, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD880</code>
	 */
	public java.lang.String getTestTableField880() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD880);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD890</code>
	 */
	public void setTestTableField890(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD890, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD890</code>
	 */
	public java.lang.String getTestTableField890() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD890);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD900</code>
	 */
	public void setTestTableField900(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD900, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD900</code>
	 */
	public java.lang.String getTestTableField900() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD900);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD910</code>
	 */
	public void setTestTableField910(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD910, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD910</code>
	 */
	public java.lang.String getTestTableField910() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD910);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD920</code>
	 */
	public void setTestTableField920(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD920, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD920</code>
	 */
	public java.lang.String getTestTableField920() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD920);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD930</code>
	 */
	public void setTestTableField930(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD930, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD930</code>
	 */
	public java.lang.String getTestTableField930() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD930);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD940</code>
	 */
	public void setTestTableField940(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD940, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD940</code>
	 */
	public java.lang.String getTestTableField940() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD940);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD950</code>
	 */
	public void setTestTableField950(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD950, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD950</code>
	 */
	public java.lang.String getTestTableField950() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD950);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD960</code>
	 */
	public void setTestTableField960(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD960, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD960</code>
	 */
	public java.lang.String getTestTableField960() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD960);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD970</code>
	 */
	public void setTestTableField970(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD970, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD970</code>
	 */
	public java.lang.String getTestTableField970() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD970);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD980</code>
	 */
	public void setTestTableField980(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD980, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD980</code>
	 */
	public java.lang.String getTestTableField980() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD980);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD990</code>
	 */
	public void setTestTableField990(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD990, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD990</code>
	 */
	public java.lang.String getTestTableField990() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD990);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD101</code>
	 */
	public void setTestTableField101(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD101, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD101</code>
	 */
	public java.lang.String getTestTableField101() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD101);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD111</code>
	 */
	public void setTestTableField111(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD111, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD111</code>
	 */
	public java.lang.String getTestTableField111() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD111);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD121</code>
	 */
	public void setTestTableField121(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD121, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD121</code>
	 */
	public java.lang.String getTestTableField121() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD121);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD131</code>
	 */
	public void setTestTableField131(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD131, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD131</code>
	 */
	public java.lang.String getTestTableField131() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD131);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD141</code>
	 */
	public void setTestTableField141(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD141, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD141</code>
	 */
	public java.lang.String getTestTableField141() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD141);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD151</code>
	 */
	public void setTestTableField151(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD151, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD151</code>
	 */
	public java.lang.String getTestTableField151() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD151);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD161</code>
	 */
	public void setTestTableField161(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD161, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD161</code>
	 */
	public java.lang.String getTestTableField161() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD161);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD171</code>
	 */
	public void setTestTableField171(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD171, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD171</code>
	 */
	public java.lang.String getTestTableField171() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD171);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD181</code>
	 */
	public void setTestTableField181(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD181, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD181</code>
	 */
	public java.lang.String getTestTableField181() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD181);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD191</code>
	 */
	public void setTestTableField191(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD191, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD191</code>
	 */
	public java.lang.String getTestTableField191() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD191);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD201</code>
	 */
	public void setTestTableField201(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD201, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD201</code>
	 */
	public java.lang.String getTestTableField201() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD201);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD211</code>
	 */
	public void setTestTableField211(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD211, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD211</code>
	 */
	public java.lang.String getTestTableField211() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD211);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD221</code>
	 */
	public void setTestTableField221(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD221, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD221</code>
	 */
	public java.lang.String getTestTableField221() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD221);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD231</code>
	 */
	public void setTestTableField231(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD231, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD231</code>
	 */
	public java.lang.String getTestTableField231() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD231);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD241</code>
	 */
	public void setTestTableField241(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD241, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD241</code>
	 */
	public java.lang.String getTestTableField241() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD241);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD251</code>
	 */
	public void setTestTableField251(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD251, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD251</code>
	 */
	public java.lang.String getTestTableField251() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD251);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD261</code>
	 */
	public void setTestTableField261(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD261, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD261</code>
	 */
	public java.lang.String getTestTableField261() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD261);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD271</code>
	 */
	public void setTestTableField271(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD271, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD271</code>
	 */
	public java.lang.String getTestTableField271() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD271);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD281</code>
	 */
	public void setTestTableField281(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD281, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD281</code>
	 */
	public java.lang.String getTestTableField281() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD281);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD291</code>
	 */
	public void setTestTableField291(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD291, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD291</code>
	 */
	public java.lang.String getTestTableField291() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD291);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD301</code>
	 */
	public void setTestTableField301(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD301, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD301</code>
	 */
	public java.lang.String getTestTableField301() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD301);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD311</code>
	 */
	public void setTestTableField311(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD311, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD311</code>
	 */
	public java.lang.String getTestTableField311() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD311);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD321</code>
	 */
	public void setTestTableField321(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD321, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD321</code>
	 */
	public java.lang.String getTestTableField321() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD321);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD331</code>
	 */
	public void setTestTableField331(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD331, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD331</code>
	 */
	public java.lang.String getTestTableField331() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD331);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD341</code>
	 */
	public void setTestTableField341(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD341, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD341</code>
	 */
	public java.lang.String getTestTableField341() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD341);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD351</code>
	 */
	public void setTestTableField351(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD351, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD351</code>
	 */
	public java.lang.String getTestTableField351() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD351);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD361</code>
	 */
	public void setTestTableField361(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD361, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD361</code>
	 */
	public java.lang.String getTestTableField361() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD361);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD371</code>
	 */
	public void setTestTableField371(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD371, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD371</code>
	 */
	public java.lang.String getTestTableField371() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD371);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD381</code>
	 */
	public void setTestTableField381(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD381, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD381</code>
	 */
	public java.lang.String getTestTableField381() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD381);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD391</code>
	 */
	public void setTestTableField391(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD391, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD391</code>
	 */
	public java.lang.String getTestTableField391() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD391);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD401</code>
	 */
	public void setTestTableField401(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD401, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD401</code>
	 */
	public java.lang.String getTestTableField401() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD401);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD411</code>
	 */
	public void setTestTableField411(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD411, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD411</code>
	 */
	public java.lang.String getTestTableField411() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD411);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD421</code>
	 */
	public void setTestTableField421(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD421, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD421</code>
	 */
	public java.lang.String getTestTableField421() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD421);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD431</code>
	 */
	public void setTestTableField431(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD431, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD431</code>
	 */
	public java.lang.String getTestTableField431() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD431);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD441</code>
	 */
	public void setTestTableField441(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD441, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD441</code>
	 */
	public java.lang.String getTestTableField441() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD441);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD451</code>
	 */
	public void setTestTableField451(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD451, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD451</code>
	 */
	public java.lang.String getTestTableField451() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD451);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD461</code>
	 */
	public void setTestTableField461(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD461, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD461</code>
	 */
	public java.lang.String getTestTableField461() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD461);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD471</code>
	 */
	public void setTestTableField471(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD471, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD471</code>
	 */
	public java.lang.String getTestTableField471() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD471);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD481</code>
	 */
	public void setTestTableField481(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD481, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD481</code>
	 */
	public java.lang.String getTestTableField481() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD481);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD491</code>
	 */
	public void setTestTableField491(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD491, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD491</code>
	 */
	public java.lang.String getTestTableField491() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD491);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD501</code>
	 */
	public void setTestTableField501(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD501, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD501</code>
	 */
	public java.lang.String getTestTableField501() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD501);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD511</code>
	 */
	public void setTestTableField511(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD511, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD511</code>
	 */
	public java.lang.String getTestTableField511() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD511);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD521</code>
	 */
	public void setTestTableField521(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD521, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD521</code>
	 */
	public java.lang.String getTestTableField521() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD521);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD531</code>
	 */
	public void setTestTableField531(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD531, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD531</code>
	 */
	public java.lang.String getTestTableField531() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD531);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD541</code>
	 */
	public void setTestTableField541(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD541, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD541</code>
	 */
	public java.lang.String getTestTableField541() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD541);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD551</code>
	 */
	public void setTestTableField551(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD551, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD551</code>
	 */
	public java.lang.String getTestTableField551() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD551);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD561</code>
	 */
	public void setTestTableField561(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD561, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD561</code>
	 */
	public java.lang.String getTestTableField561() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD561);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD571</code>
	 */
	public void setTestTableField571(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD571, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD571</code>
	 */
	public java.lang.String getTestTableField571() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD571);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD581</code>
	 */
	public void setTestTableField581(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD581, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD581</code>
	 */
	public java.lang.String getTestTableField581() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD581);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD591</code>
	 */
	public void setTestTableField591(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD591, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD591</code>
	 */
	public java.lang.String getTestTableField591() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD591);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD601</code>
	 */
	public void setTestTableField601(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD601, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD601</code>
	 */
	public java.lang.String getTestTableField601() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD601);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD611</code>
	 */
	public void setTestTableField611(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD611, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD611</code>
	 */
	public java.lang.String getTestTableField611() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD611);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD621</code>
	 */
	public void setTestTableField621(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD621, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD621</code>
	 */
	public java.lang.String getTestTableField621() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD621);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD631</code>
	 */
	public void setTestTableField631(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD631, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD631</code>
	 */
	public java.lang.String getTestTableField631() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD631);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD641</code>
	 */
	public void setTestTableField641(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD641, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD641</code>
	 */
	public java.lang.String getTestTableField641() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD641);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD651</code>
	 */
	public void setTestTableField651(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD651, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD651</code>
	 */
	public java.lang.String getTestTableField651() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD651);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD661</code>
	 */
	public void setTestTableField661(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD661, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD661</code>
	 */
	public java.lang.String getTestTableField661() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD661);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD671</code>
	 */
	public void setTestTableField671(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD671, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD671</code>
	 */
	public java.lang.String getTestTableField671() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD671);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD681</code>
	 */
	public void setTestTableField681(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD681, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD681</code>
	 */
	public java.lang.String getTestTableField681() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD681);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD691</code>
	 */
	public void setTestTableField691(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD691, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD691</code>
	 */
	public java.lang.String getTestTableField691() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD691);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD701</code>
	 */
	public void setTestTableField701(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD701, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD701</code>
	 */
	public java.lang.String getTestTableField701() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD701);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD711</code>
	 */
	public void setTestTableField711(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD711, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD711</code>
	 */
	public java.lang.String getTestTableField711() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD711);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD721</code>
	 */
	public void setTestTableField721(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD721, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD721</code>
	 */
	public java.lang.String getTestTableField721() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD721);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD731</code>
	 */
	public void setTestTableField731(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD731, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD731</code>
	 */
	public java.lang.String getTestTableField731() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD731);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD741</code>
	 */
	public void setTestTableField741(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD741, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD741</code>
	 */
	public java.lang.String getTestTableField741() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD741);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD751</code>
	 */
	public void setTestTableField751(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD751, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD751</code>
	 */
	public java.lang.String getTestTableField751() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD751);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD761</code>
	 */
	public void setTestTableField761(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD761, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD761</code>
	 */
	public java.lang.String getTestTableField761() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD761);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD771</code>
	 */
	public void setTestTableField771(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD771, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD771</code>
	 */
	public java.lang.String getTestTableField771() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD771);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD781</code>
	 */
	public void setTestTableField781(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD781, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD781</code>
	 */
	public java.lang.String getTestTableField781() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD781);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD791</code>
	 */
	public void setTestTableField791(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD791, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD791</code>
	 */
	public java.lang.String getTestTableField791() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD791);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD801</code>
	 */
	public void setTestTableField801(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD801, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD801</code>
	 */
	public java.lang.String getTestTableField801() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD801);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD811</code>
	 */
	public void setTestTableField811(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD811, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD811</code>
	 */
	public java.lang.String getTestTableField811() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD811);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD821</code>
	 */
	public void setTestTableField821(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD821, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD821</code>
	 */
	public java.lang.String getTestTableField821() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD821);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD831</code>
	 */
	public void setTestTableField831(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD831, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD831</code>
	 */
	public java.lang.String getTestTableField831() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD831);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD841</code>
	 */
	public void setTestTableField841(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD841, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD841</code>
	 */
	public java.lang.String getTestTableField841() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD841);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD851</code>
	 */
	public void setTestTableField851(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD851, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD851</code>
	 */
	public java.lang.String getTestTableField851() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD851);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD861</code>
	 */
	public void setTestTableField861(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD861, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD861</code>
	 */
	public java.lang.String getTestTableField861() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD861);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD871</code>
	 */
	public void setTestTableField871(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD871, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD871</code>
	 */
	public java.lang.String getTestTableField871() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD871);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD881</code>
	 */
	public void setTestTableField881(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD881, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD881</code>
	 */
	public java.lang.String getTestTableField881() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD881);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD891</code>
	 */
	public void setTestTableField891(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD891, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD891</code>
	 */
	public java.lang.String getTestTableField891() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD891);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD901</code>
	 */
	public void setTestTableField901(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD901, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD901</code>
	 */
	public java.lang.String getTestTableField901() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD901);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD911</code>
	 */
	public void setTestTableField911(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD911, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD911</code>
	 */
	public java.lang.String getTestTableField911() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD911);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD921</code>
	 */
	public void setTestTableField921(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD921, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD921</code>
	 */
	public java.lang.String getTestTableField921() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD921);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD931</code>
	 */
	public void setTestTableField931(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD931, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD931</code>
	 */
	public java.lang.String getTestTableField931() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD931);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD941</code>
	 */
	public void setTestTableField941(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD941, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD941</code>
	 */
	public java.lang.String getTestTableField941() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD941);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD951</code>
	 */
	public void setTestTableField951(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD951, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD951</code>
	 */
	public java.lang.String getTestTableField951() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD951);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD961</code>
	 */
	public void setTestTableField961(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD961, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD961</code>
	 */
	public java.lang.String getTestTableField961() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD961);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD971</code>
	 */
	public void setTestTableField971(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD971, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD971</code>
	 */
	public java.lang.String getTestTableField971() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD971);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD981</code>
	 */
	public void setTestTableField981(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD981, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD981</code>
	 */
	public java.lang.String getTestTableField981() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD981);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD991</code>
	 */
	public void setTestTableField991(java.lang.String value) {
		setValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD991, value);
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD991</code>
	 */
	public java.lang.String getTestTableField991() {
		return getValue(test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_FIELD991);
	}

	/**
	 * Create a detached TestTable12Record
	 */
	public TestTable12Record() {
		super(test.schema.tables.TestTable12.TEST_TABLE12);
	}
}
