/**
 * This class is generated by jOOQ
 */
package test.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public class TestTable12 extends org.jooq.impl.UpdatableTableImpl<test.schema.tables.records.TestTable12Record> {

	private static final long serialVersionUID = -1698680519;

	/**
	 * The singleton instance of UPS.TEST_TABLE12
	 */
	public static final test.schema.tables.TestTable12 TEST_TABLE12 = new test.schema.tables.TestTable12();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<test.schema.tables.records.TestTable12Record> getRecordType() {
		return test.schema.tables.records.TestTable12Record.class;
	}

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.Long> TEST_TABLE_ID = createField("TEST_TABLE_ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD100</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD100 = createField("TEST_TABLE_FIELD100", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD110</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD110 = createField("TEST_TABLE_FIELD110", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD120</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD120 = createField("TEST_TABLE_FIELD120", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD130</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD130 = createField("TEST_TABLE_FIELD130", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD140</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD140 = createField("TEST_TABLE_FIELD140", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD150</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD150 = createField("TEST_TABLE_FIELD150", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD160</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD160 = createField("TEST_TABLE_FIELD160", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD170</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD170 = createField("TEST_TABLE_FIELD170", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD180</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD180 = createField("TEST_TABLE_FIELD180", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD190</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD190 = createField("TEST_TABLE_FIELD190", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD200</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD200 = createField("TEST_TABLE_FIELD200", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD210</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD210 = createField("TEST_TABLE_FIELD210", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD220</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD220 = createField("TEST_TABLE_FIELD220", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD230</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD230 = createField("TEST_TABLE_FIELD230", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD240</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD240 = createField("TEST_TABLE_FIELD240", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD250</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD250 = createField("TEST_TABLE_FIELD250", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD260</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD260 = createField("TEST_TABLE_FIELD260", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD270</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD270 = createField("TEST_TABLE_FIELD270", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD280</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD280 = createField("TEST_TABLE_FIELD280", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD290</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD290 = createField("TEST_TABLE_FIELD290", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD300</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD300 = createField("TEST_TABLE_FIELD300", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD310</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD310 = createField("TEST_TABLE_FIELD310", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD320</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD320 = createField("TEST_TABLE_FIELD320", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD330</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD330 = createField("TEST_TABLE_FIELD330", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD340</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD340 = createField("TEST_TABLE_FIELD340", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD350</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD350 = createField("TEST_TABLE_FIELD350", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD360</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD360 = createField("TEST_TABLE_FIELD360", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD370</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD370 = createField("TEST_TABLE_FIELD370", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD380</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD380 = createField("TEST_TABLE_FIELD380", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD390</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD390 = createField("TEST_TABLE_FIELD390", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD400</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD400 = createField("TEST_TABLE_FIELD400", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD410</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD410 = createField("TEST_TABLE_FIELD410", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD420</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD420 = createField("TEST_TABLE_FIELD420", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD430</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD430 = createField("TEST_TABLE_FIELD430", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD440</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD440 = createField("TEST_TABLE_FIELD440", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD450</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD450 = createField("TEST_TABLE_FIELD450", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD460</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD460 = createField("TEST_TABLE_FIELD460", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD470</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD470 = createField("TEST_TABLE_FIELD470", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD480</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD480 = createField("TEST_TABLE_FIELD480", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD490</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD490 = createField("TEST_TABLE_FIELD490", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD500</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD500 = createField("TEST_TABLE_FIELD500", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD510</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD510 = createField("TEST_TABLE_FIELD510", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD520</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD520 = createField("TEST_TABLE_FIELD520", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD530</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD530 = createField("TEST_TABLE_FIELD530", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD540</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD540 = createField("TEST_TABLE_FIELD540", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD550</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD550 = createField("TEST_TABLE_FIELD550", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD560</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD560 = createField("TEST_TABLE_FIELD560", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD570</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD570 = createField("TEST_TABLE_FIELD570", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD580</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD580 = createField("TEST_TABLE_FIELD580", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD590</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD590 = createField("TEST_TABLE_FIELD590", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD600</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD600 = createField("TEST_TABLE_FIELD600", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD610</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD610 = createField("TEST_TABLE_FIELD610", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD620</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD620 = createField("TEST_TABLE_FIELD620", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD630</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD630 = createField("TEST_TABLE_FIELD630", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD640</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD640 = createField("TEST_TABLE_FIELD640", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD650</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD650 = createField("TEST_TABLE_FIELD650", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD660</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD660 = createField("TEST_TABLE_FIELD660", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD670</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD670 = createField("TEST_TABLE_FIELD670", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD680</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD680 = createField("TEST_TABLE_FIELD680", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD690</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD690 = createField("TEST_TABLE_FIELD690", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD700</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD700 = createField("TEST_TABLE_FIELD700", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD710</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD710 = createField("TEST_TABLE_FIELD710", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD720</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD720 = createField("TEST_TABLE_FIELD720", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD730</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD730 = createField("TEST_TABLE_FIELD730", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD740</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD740 = createField("TEST_TABLE_FIELD740", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD750</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD750 = createField("TEST_TABLE_FIELD750", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD760</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD760 = createField("TEST_TABLE_FIELD760", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD770</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD770 = createField("TEST_TABLE_FIELD770", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD780</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD780 = createField("TEST_TABLE_FIELD780", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD790</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD790 = createField("TEST_TABLE_FIELD790", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD800</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD800 = createField("TEST_TABLE_FIELD800", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD810</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD810 = createField("TEST_TABLE_FIELD810", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD820</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD820 = createField("TEST_TABLE_FIELD820", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD830</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD830 = createField("TEST_TABLE_FIELD830", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD840</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD840 = createField("TEST_TABLE_FIELD840", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD850</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD850 = createField("TEST_TABLE_FIELD850", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD860</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD860 = createField("TEST_TABLE_FIELD860", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD870</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD870 = createField("TEST_TABLE_FIELD870", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD880</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD880 = createField("TEST_TABLE_FIELD880", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD890</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD890 = createField("TEST_TABLE_FIELD890", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD900</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD900 = createField("TEST_TABLE_FIELD900", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD910</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD910 = createField("TEST_TABLE_FIELD910", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD920</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD920 = createField("TEST_TABLE_FIELD920", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD930</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD930 = createField("TEST_TABLE_FIELD930", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD940</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD940 = createField("TEST_TABLE_FIELD940", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD950</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD950 = createField("TEST_TABLE_FIELD950", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD960</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD960 = createField("TEST_TABLE_FIELD960", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD970</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD970 = createField("TEST_TABLE_FIELD970", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD980</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD980 = createField("TEST_TABLE_FIELD980", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD990</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD990 = createField("TEST_TABLE_FIELD990", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD101</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD101 = createField("TEST_TABLE_FIELD101", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD111</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD111 = createField("TEST_TABLE_FIELD111", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD121</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD121 = createField("TEST_TABLE_FIELD121", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD131</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD131 = createField("TEST_TABLE_FIELD131", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD141</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD141 = createField("TEST_TABLE_FIELD141", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD151</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD151 = createField("TEST_TABLE_FIELD151", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD161</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD161 = createField("TEST_TABLE_FIELD161", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD171</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD171 = createField("TEST_TABLE_FIELD171", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD181</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD181 = createField("TEST_TABLE_FIELD181", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD191</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD191 = createField("TEST_TABLE_FIELD191", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD201</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD201 = createField("TEST_TABLE_FIELD201", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD211</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD211 = createField("TEST_TABLE_FIELD211", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD221</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD221 = createField("TEST_TABLE_FIELD221", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD231</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD231 = createField("TEST_TABLE_FIELD231", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD241</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD241 = createField("TEST_TABLE_FIELD241", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD251</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD251 = createField("TEST_TABLE_FIELD251", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD261</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD261 = createField("TEST_TABLE_FIELD261", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD271</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD271 = createField("TEST_TABLE_FIELD271", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD281</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD281 = createField("TEST_TABLE_FIELD281", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD291</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD291 = createField("TEST_TABLE_FIELD291", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD301</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD301 = createField("TEST_TABLE_FIELD301", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD311</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD311 = createField("TEST_TABLE_FIELD311", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD321</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD321 = createField("TEST_TABLE_FIELD321", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD331</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD331 = createField("TEST_TABLE_FIELD331", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD341</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD341 = createField("TEST_TABLE_FIELD341", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD351</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD351 = createField("TEST_TABLE_FIELD351", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD361</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD361 = createField("TEST_TABLE_FIELD361", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD371</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD371 = createField("TEST_TABLE_FIELD371", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD381</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD381 = createField("TEST_TABLE_FIELD381", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD391</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD391 = createField("TEST_TABLE_FIELD391", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD401</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD401 = createField("TEST_TABLE_FIELD401", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD411</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD411 = createField("TEST_TABLE_FIELD411", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD421</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD421 = createField("TEST_TABLE_FIELD421", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD431</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD431 = createField("TEST_TABLE_FIELD431", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD441</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD441 = createField("TEST_TABLE_FIELD441", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD451</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD451 = createField("TEST_TABLE_FIELD451", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD461</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD461 = createField("TEST_TABLE_FIELD461", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD471</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD471 = createField("TEST_TABLE_FIELD471", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD481</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD481 = createField("TEST_TABLE_FIELD481", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD491</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD491 = createField("TEST_TABLE_FIELD491", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD501</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD501 = createField("TEST_TABLE_FIELD501", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD511</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD511 = createField("TEST_TABLE_FIELD511", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD521</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD521 = createField("TEST_TABLE_FIELD521", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD531</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD531 = createField("TEST_TABLE_FIELD531", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD541</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD541 = createField("TEST_TABLE_FIELD541", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD551</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD551 = createField("TEST_TABLE_FIELD551", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD561</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD561 = createField("TEST_TABLE_FIELD561", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD571</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD571 = createField("TEST_TABLE_FIELD571", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD581</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD581 = createField("TEST_TABLE_FIELD581", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD591</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD591 = createField("TEST_TABLE_FIELD591", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD601</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD601 = createField("TEST_TABLE_FIELD601", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD611</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD611 = createField("TEST_TABLE_FIELD611", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD621</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD621 = createField("TEST_TABLE_FIELD621", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD631</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD631 = createField("TEST_TABLE_FIELD631", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD641</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD641 = createField("TEST_TABLE_FIELD641", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD651</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD651 = createField("TEST_TABLE_FIELD651", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD661</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD661 = createField("TEST_TABLE_FIELD661", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD671</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD671 = createField("TEST_TABLE_FIELD671", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD681</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD681 = createField("TEST_TABLE_FIELD681", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD691</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD691 = createField("TEST_TABLE_FIELD691", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD701</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD701 = createField("TEST_TABLE_FIELD701", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD711</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD711 = createField("TEST_TABLE_FIELD711", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD721</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD721 = createField("TEST_TABLE_FIELD721", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD731</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD731 = createField("TEST_TABLE_FIELD731", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD741</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD741 = createField("TEST_TABLE_FIELD741", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD751</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD751 = createField("TEST_TABLE_FIELD751", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD761</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD761 = createField("TEST_TABLE_FIELD761", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD771</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD771 = createField("TEST_TABLE_FIELD771", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD781</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD781 = createField("TEST_TABLE_FIELD781", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD791</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD791 = createField("TEST_TABLE_FIELD791", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD801</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD801 = createField("TEST_TABLE_FIELD801", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD811</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD811 = createField("TEST_TABLE_FIELD811", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD821</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD821 = createField("TEST_TABLE_FIELD821", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD831</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD831 = createField("TEST_TABLE_FIELD831", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD841</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD841 = createField("TEST_TABLE_FIELD841", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD851</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD851 = createField("TEST_TABLE_FIELD851", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD861</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD861 = createField("TEST_TABLE_FIELD861", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD871</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD871 = createField("TEST_TABLE_FIELD871", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD881</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD881 = createField("TEST_TABLE_FIELD881", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD891</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD891 = createField("TEST_TABLE_FIELD891", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD901</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD901 = createField("TEST_TABLE_FIELD901", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD911</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD911 = createField("TEST_TABLE_FIELD911", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD921</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD921 = createField("TEST_TABLE_FIELD921", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD931</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD931 = createField("TEST_TABLE_FIELD931", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD941</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD941 = createField("TEST_TABLE_FIELD941", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD951</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD951 = createField("TEST_TABLE_FIELD951", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD961</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD961 = createField("TEST_TABLE_FIELD961", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD971</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD971 = createField("TEST_TABLE_FIELD971", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD981</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD981 = createField("TEST_TABLE_FIELD981", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>UPS.TEST_TABLE12.TEST_TABLE_FIELD991</code>
	 */
	public final org.jooq.TableField<test.schema.tables.records.TestTable12Record, java.lang.String> TEST_TABLE_FIELD991 = createField("TEST_TABLE_FIELD991", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TestTable12() {
		super("TEST_TABLE12", test.schema.Ups.UPS);
	}

	public TestTable12(java.lang.String alias) {
		super(alias, test.schema.Ups.UPS, test.schema.tables.TestTable12.TEST_TABLE12);
	}

	@Override
	public org.jooq.UniqueKey<test.schema.tables.records.TestTable12Record> getMainKey() {
		return test.schema.Keys.PK_TEST_TABLE12;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<test.schema.tables.records.TestTable12Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<test.schema.tables.records.TestTable12Record>>asList(test.schema.Keys.PK_TEST_TABLE12);
	}

	@Override
	public test.schema.tables.TestTable12 as(java.lang.String alias) {
		return new test.schema.tables.TestTable12(alias);
	}
}
