/**
 * This class is generated by jOOQ
 */
package test.schema;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>UPS</code> 
 * schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public class Keys {

	// IDENTITY definitions

	// UNIQUE and PRIMARY KEY definitions
	public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable10Record> PK_TEST_TABLE10 = UniqueKeys0.PK_TEST_TABLE10;
	public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable11Record> PK_TEST_TABLE11 = UniqueKeys0.PK_TEST_TABLE11;
	public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable12Record> PK_TEST_TABLE12 = UniqueKeys0.PK_TEST_TABLE12;
	public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable13Record> PK_TEST_TABLE13 = UniqueKeys0.PK_TEST_TABLE13;
	public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable14Record> PK_TEST_TABLE14 = UniqueKeys0.PK_TEST_TABLE14;
	public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable15Record> PK_TEST_TABLE15 = UniqueKeys0.PK_TEST_TABLE15;
	public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable16Record> PK_TEST_TABLE16 = UniqueKeys0.PK_TEST_TABLE16;
	public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable17Record> PK_TEST_TABLE17 = UniqueKeys0.PK_TEST_TABLE17;
	public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable18Record> PK_TEST_TABLE18 = UniqueKeys0.PK_TEST_TABLE18;
	public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable19Record> PK_TEST_TABLE19 = UniqueKeys0.PK_TEST_TABLE19;

	// FOREIGN KEY definitions

	/**
	 * No instances
	 */
	private Keys() {}

	@SuppressWarnings({"hiding", "unchecked"})
	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable10Record> PK_TEST_TABLE10 = createUniqueKey(test.schema.tables.TestTable10.TEST_TABLE10, test.schema.tables.TestTable10.TEST_TABLE10.TEST_TABLE_ID);
		public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable11Record> PK_TEST_TABLE11 = createUniqueKey(test.schema.tables.TestTable11.TEST_TABLE11, test.schema.tables.TestTable11.TEST_TABLE11.TEST_TABLE_ID);
		public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable12Record> PK_TEST_TABLE12 = createUniqueKey(test.schema.tables.TestTable12.TEST_TABLE12, test.schema.tables.TestTable12.TEST_TABLE12.TEST_TABLE_ID);
		public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable13Record> PK_TEST_TABLE13 = createUniqueKey(test.schema.tables.TestTable13.TEST_TABLE13, test.schema.tables.TestTable13.TEST_TABLE13.TEST_TABLE_ID);
		public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable14Record> PK_TEST_TABLE14 = createUniqueKey(test.schema.tables.TestTable14.TEST_TABLE14, test.schema.tables.TestTable14.TEST_TABLE14.TEST_TABLE_ID);
		public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable15Record> PK_TEST_TABLE15 = createUniqueKey(test.schema.tables.TestTable15.TEST_TABLE15, test.schema.tables.TestTable15.TEST_TABLE15.TEST_TABLE_ID);
		public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable16Record> PK_TEST_TABLE16 = createUniqueKey(test.schema.tables.TestTable16.TEST_TABLE16, test.schema.tables.TestTable16.TEST_TABLE16.TEST_TABLE_ID);
		public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable17Record> PK_TEST_TABLE17 = createUniqueKey(test.schema.tables.TestTable17.TEST_TABLE17, test.schema.tables.TestTable17.TEST_TABLE17.TEST_TABLE_ID);
		public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable18Record> PK_TEST_TABLE18 = createUniqueKey(test.schema.tables.TestTable18.TEST_TABLE18, test.schema.tables.TestTable18.TEST_TABLE18.TEST_TABLE_ID);
		public static final org.jooq.UniqueKey<test.schema.tables.records.TestTable19Record> PK_TEST_TABLE19 = createUniqueKey(test.schema.tables.TestTable19.TEST_TABLE19, test.schema.tables.TestTable19.TEST_TABLE19.TEST_TABLE_ID);
	}
}
