/**
 * This class is generated by jOOQ
 */
package test.schema;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in UPS
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public final class Tables {

	/**
	 * The table UPS.TEST_TABLE10
	 */
	public static final test.schema.tables.TestTable10 TEST_TABLE10 = test.schema.tables.TestTable10.TEST_TABLE10;

	/**
	 * The table UPS.TEST_TABLE11
	 */
	public static final test.schema.tables.TestTable11 TEST_TABLE11 = test.schema.tables.TestTable11.TEST_TABLE11;

	/**
	 * The table UPS.TEST_TABLE12
	 */
	public static final test.schema.tables.TestTable12 TEST_TABLE12 = test.schema.tables.TestTable12.TEST_TABLE12;

	/**
	 * The table UPS.TEST_TABLE13
	 */
	public static final test.schema.tables.TestTable13 TEST_TABLE13 = test.schema.tables.TestTable13.TEST_TABLE13;

	/**
	 * The table UPS.TEST_TABLE14
	 */
	public static final test.schema.tables.TestTable14 TEST_TABLE14 = test.schema.tables.TestTable14.TEST_TABLE14;

	/**
	 * The table UPS.TEST_TABLE15
	 */
	public static final test.schema.tables.TestTable15 TEST_TABLE15 = test.schema.tables.TestTable15.TEST_TABLE15;

	/**
	 * The table UPS.TEST_TABLE16
	 */
	public static final test.schema.tables.TestTable16 TEST_TABLE16 = test.schema.tables.TestTable16.TEST_TABLE16;

	/**
	 * The table UPS.TEST_TABLE17
	 */
	public static final test.schema.tables.TestTable17 TEST_TABLE17 = test.schema.tables.TestTable17.TEST_TABLE17;

	/**
	 * The table UPS.TEST_TABLE18
	 */
	public static final test.schema.tables.TestTable18 TEST_TABLE18 = test.schema.tables.TestTable18.TEST_TABLE18;

	/**
	 * The table UPS.TEST_TABLE19
	 */
	public static final test.schema.tables.TestTable19 TEST_TABLE19 = test.schema.tables.TestTable19.TEST_TABLE19;

	/**
	 * No instances
	 */
	private Tables() {}
}
