/**
 * This class is generated by jOOQ
 */
package test.schema;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public class Ups extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -131900028;

	/**
	 * The singleton instance of UPS
	 */
	public static final Ups UPS = new Ups();

	/**
	 * No further instances allowed
	 */
	private Ups() {
		super("UPS");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			test.schema.tables.TestTable10.TEST_TABLE10,
			test.schema.tables.TestTable11.TEST_TABLE11,
			test.schema.tables.TestTable12.TEST_TABLE12,
			test.schema.tables.TestTable13.TEST_TABLE13,
			test.schema.tables.TestTable14.TEST_TABLE14,
			test.schema.tables.TestTable15.TEST_TABLE15,
			test.schema.tables.TestTable16.TEST_TABLE16,
			test.schema.tables.TestTable17.TEST_TABLE17,
			test.schema.tables.TestTable18.TEST_TABLE18,
			test.schema.tables.TestTable19.TEST_TABLE19);
	}
}
